### ISSUE TITLE
Inconsistent accept() behavior

### ISSUE THREAD

**Issue by supahero1** [BlueCannonBall/Polynet#1]
`polynet.cpp` line 97, accepting stops with an error once the call to `accept()` also errors out, however errors here don't necessarily indicate a fatal failure - both under Linux and Windows (`ECONNABORTED` and `WSAECONNRESET` respectively, which are not fatal errors). I suggest the code checks the specific error before telling the application something bad happened, possibly making it crash or quit altogether, allowing an easy DOS.

**Comment by Altanis** [comment]
make a pr to fix this

**Comment by BlueCannonBall** [comment]
Fixed.
